const initialContracts = [
  {
    ContractId: "CT001",
    Username: "johndoe",
    Menu: 1,
    EventId: 101,
    DateCreate: "2024-09-01T10:30:00",
    OrganizDate: "2024-09-10T15:00:00",
    LocationId: 5,
    ContractType: "Service",
    TotalMoney: 500000,
    PaymentStatus: "Paid",
    ContractStatus: "Active",
    Description: "Catering service for event",
    CustomerName: "John Doe",
    CustomerPhone: "+123456789",
    CustomerEmail: "john.doe@example.com",
    IsDeleted: false,
  },
  {
    ContractId: "CT002",
    Username: "janedoe",
    Menu: 2,
    EventId: 102,
    DateCreate: "2024-09-05T11:00:00",
    OrganizDate: "2024-09-15T18:00:00",
    LocationId: 8,
    ContractType: "Rental",
    TotalMoney: 300000,
    PaymentStatus: "Pending",
    ContractStatus: "Pending",
    Description: "Rental of event equipment",
    CustomerName: "Jane Doe",
    CustomerPhone: "+987654321",
    CustomerEmail: "jane.doe@example.com",
    IsDeleted: false,
  },
  {
    ContractId: "CT003",
    Username: "smith123",
    Menu: 3,
    EventId: 103,
    DateCreate: "2024-09-07T09:45:00",
    OrganizDate: "2024-09-20T14:00:00",
    LocationId: 12,
    ContractType: "Consulting",
    TotalMoney: 200000,
    PaymentStatus: "Paid",
    ContractStatus: "Completed",
    Description: "Event planning consultancy",
    CustomerName: "Robert Smith",
    CustomerPhone: "+1122334455",
    CustomerEmail: "robert.smith@example.com",
    IsDeleted: false,
  },
  {
    ContractId: "CT004",
    Username: "maryjane",
    Menu: 4,
    EventId: 104,
    DateCreate: "2024-09-10T08:15:00",
    OrganizDate: "2024-09-25T12:00:00",
    LocationId: 15,
    ContractType: "Service",
    TotalMoney: 400000,
    PaymentStatus: "Pending",
    ContractStatus: "Cancelled",
    Description: "Event decoration services",
    CustomerName: "Mary Jane",
    CustomerPhone: "+122334455",
    CustomerEmail: "mary.jane@example.com",
    IsDeleted: true,
  },
  {
    ContractId: "CT005",
    Username: "alicew",
    Menu: 5,
    EventId: 105,
    DateCreate: "2024-09-11T14:30:00",
    OrganizDate: "2024-09-30T10:00:00",
    LocationId: 3,
    ContractType: "Consulting",
    TotalMoney: 120000,
    PaymentStatus: "Unpaid",
    ContractStatus: "Active",
    Description: "Marketing consultancy for product launch",
    CustomerName: "Alice White",
    CustomerPhone: "+1231231234",
    CustomerEmail: "alice.white@example.com",
    IsDeleted: false,
  },
  {
    ContractId: "CT006",
    Username: "charlesb",
    Menu: 6,
    EventId: 106,
    DateCreate: "2024-09-12T09:00:00",
    OrganizDate: "2024-10-05T16:00:00",
    LocationId: 10,
    ContractType: "Service",
    TotalMoney: 220000,
    PaymentStatus: "Paid",
    ContractStatus: "Completed",
    Description: "Audio-visual services for corporate event",
    CustomerName: "Charles Brown",
    CustomerPhone: "+9879879876",
    CustomerEmail: "charles.brown@example.com",
    IsDeleted: false,
  },
  {
    ContractId: "CT007",
    Username: "davidg",
    Menu: 7,
    EventId: 107,
    DateCreate: "2024-09-15T11:15:00",
    OrganizDate: "2024-10-10T14:00:00",
    LocationId: 6,
    ContractType: "Rental",
    TotalMoney: 500000,
    PaymentStatus: "Pending",
    ContractStatus: "Pending",
    Description: "Rental of furniture for wedding",
    CustomerName: "David Green",
    CustomerPhone: "+3213213210",
    CustomerEmail: "david.green@example.com",
    IsDeleted: false,
  },
  {
    ContractId: "CT008",
    Username: "emilyh",
    Menu: 8,
    EventId: 108,
    DateCreate: "2024-09-18T13:45:00",
    OrganizDate: "2024-10-15T19:00:00",
    LocationId: 4,
    ContractType: "Service",
    TotalMoney: 1000000,
    PaymentStatus: "Paid",
    ContractStatus: "Active",
    Description: "Catering for wedding reception",
    CustomerName: "Emily Harris",
    CustomerPhone: "+4564564567",
    CustomerEmail: "emily.harris@example.com",
    IsDeleted: false,
  },
  {
    ContractId: "CT009",
    Username: "frankk",
    Menu: 9,
    EventId: 109,
    DateCreate: "2024-09-20T10:00:00",
    OrganizDate: "2024-10-20T11:00:00",
    LocationId: 7,
    ContractType: "Consulting",
    TotalMoney: 400000,
    PaymentStatus: "Unpaid",
    ContractStatus: "Cancelled",
    Description: "Consulting for non-profit organization",
    CustomerName: "Frank King",
    CustomerPhone: "+7897897890",
    CustomerEmail: "frank.king@example.com",
    IsDeleted: true,
  },
  {
    ContractId: "CT010",
    Username: "gracej",
    Menu: 10,
    EventId: 110,
    DateCreate: "2024-09-22T14:20:00",
    OrganizDate: "2024-10-25T15:30:00",
    LocationId: 9,
    ContractType: "Rental",
    TotalMoney: 600000,
    PaymentStatus: "Paid",
    ContractStatus: "Completed",
    Description: "Rental of sound equipment for concert",
    CustomerName: "Grace Johnson",
    CustomerPhone: "+6546546543",
    CustomerEmail: "grace.johnson@example.com",
    IsDeleted: false,
  },
  {
    ContractId: "CT010",
    Username: "gracej",
    Menu: 11,
    EventId: 110,
    DateCreate: "2024-09-22T14:20:00",
    OrganizDate: "2024-10-25T15:30:00",
    LocationId: 9,
    ContractType: "Rental",
    TotalMoney: 600000,
    PaymentStatus: "Paid",
    ContractStatus: "Completed",
    Description: "Rental of sound equipment for concert",
    CustomerName: "Grace Johnson",
    CustomerPhone: "+6546546543",
    CustomerEmail: "grace.johnson@example.com",
    IsDeleted: false,
  },
];
const stockRequests = [
  {
    RequestId: 1,
    ContractId: 101,
    IngredientId: 501,
    RequestedQuantity: 100,
    ApprovalStatus: "Pending",
    ReceivedDate: "2023-09-10T10:00:00",
    RequestDate: "2023-09-08T08:30:00",
    Status: "Open",
  },
  {
    RequestId: 4,
    ContractId: 101,
    IngredientId: 501,
    RequestedQuantity: 100,
    ApprovalStatus: "Pending",
    ReceivedDate: "2023-09-10T10:00:00",
    RequestDate: "2023-09-08T08:30:00",
    Status: "Open",
  },

  {
    RequestId: 2,
    ContractId: 102,
    IngredientId: 502,
    RequestedQuantity: 150,
    ApprovalStatus: "Approved",
    ReceivedDate: "2023-09-11T09:00:00",
    RequestDate: "2023-09-09T07:45:00",
    Status: "Closed",
  },
  {
    RequestId: 3,
    ContractId: 103,
    IngredientId: 503,
    RequestedQuantity: 200,
    ApprovalStatus: "Rejected",
    ReceivedDate: "2023-09-12T11:15:00",
    RequestDate: "2023-09-10T06:50:00",
    Status: "Closed",
  },
];
const initialServices = [
  {
    ServiceId: 1,
    ServiceName: "Table Reservation",
    Description: "Reservation service for VIP tables or special occasions.",
    ServiceType: "Reservation",
    Availability: true,
    Price: 500000,
    IsDeleted: false,
  },
  {
    ServiceId: 2,
    ServiceName: "Catering",
    Description: "Catering service for parties, events, and corporate meetings.",
    ServiceType: "Event Service",
    Availability: true,
    Price: 500000,
    IsDeleted: false,
  },
  {
    ServiceId: 3,
    ServiceName: "Private Chef",
    Description: "Personalized chef service for in-house dining experiences.",
    ServiceType: "Premium",
    Availability: false,
    Price: 100000,
    IsDeleted: true,
  },
  {
    ServiceId: 4,
    ServiceName: "Outdoor Seating",
    Description: "Special seating in the outdoor garden area.",
    ServiceType: "Seating",
    Availability: true,
    Price: 200000,
    IsDeleted: false,
  },
  {
    ServiceId: 5,
    ServiceName: "Live Music",
    Description: "Live music performances during dinner hours.",
    ServiceType: "Entertainment",
    Availability: true,
    Price: 150000,
    IsDeleted: false,
  },
  {
    ServiceId: 6,
    ServiceName: "Wine Tasting",
    Description: "Exclusive wine tasting experience with expert sommeliers.",
    ServiceType: "Event Service",
    Availability: true,
    Price: 300000,
    IsDeleted: false,
  },
  {
    ServiceId: 7,
    ServiceName: "Wine Tasting",
    Description: "Exclusive wine tasting experience with expert sommeliers.",
    ServiceType: "Event Service",
    Availability: true,
    Price: 300000,
    IsDeleted: false,
  },
  {
    ServiceId: 8,
    ServiceName: "Wine Tasting",
    Description: "Exclusive wine tasting experience with expert sommeliers.",
    ServiceType: "Event Service",
    Availability: true,
    Price: 300000,
    IsDeleted: false,
  },
  {
    ServiceId: 9,
    ServiceName: "Wine Tasting",
    Description: "Exclusive wine tasting experience with expert sommeliers.",
    ServiceType: "Event Service",
    Availability: true,
    Price: 300000,
    IsDeleted: false,
  },
];

const initialEvents = [
  {
    EventId: 1,
    EventName: "Tech Conference 2024",
    Description: "A conference discussing the latest in tech innovations.",
    TotalCost: 10000.5,
    IsDeleted: false,
  },
  {
    EventId: 2,
    EventName: "Music Festival",
    Description: "Annual music festival featuring local artists.",
    TotalCost: 7500.0,
    IsDeleted: false,
  },
  {
    EventId: 3,
    EventName: "Charity Run",
    Description: "5k charity run to raise funds for healthcare.",
    TotalCost: 1200.75,
    IsDeleted: true,
  },
  {
    EventId: 4,
    EventName: "Startup Pitch Night",
    Description: "Pitch your startup idea to investors and win funding.",
    TotalCost: 500.0,
    IsDeleted: false,
  },
  {
    EventId: 5,
    EventName: "Art Exhibition",
    Description: "Showcase of modern art by emerging artists.",
    TotalCost: 1500.3,
    IsDeleted: false,
  },
  {
    EventId: 6,
    EventName: "Food & Wine Expo",
    Description: "An expo showcasing gourmet food and fine wines from around the world.",
    TotalCost: 8200.0,
    IsDeleted: false,
  },
  {
    EventId: 7,
    EventName: "Health & Wellness Retreat",
    Description: "A weekend retreat focused on physical and mental wellness.",
    TotalCost: 4000.75,
    IsDeleted: false,
  },
  {
    EventId: 8,
    EventName: "Film Premiere Night",
    Description: "Premiere of an independent film followed by a Q&A with the director.",
    TotalCost: 3500.25,
    IsDeleted: false,
  },
  {
    EventId: 9,
    EventName: "Book Fair",
    Description: "A fair where local authors can showcase and sell their latest books.",
    TotalCost: 1800.9,
    IsDeleted: true,
  },
  {
    EventId: 10,
    EventName: "Science Fair",
    Description: "A science fair for students to present their innovative projects.",
    TotalCost: 2200.0,
    IsDeleted: false,
  },
];
const initialLocations = [
  {
    LocationId: 1,
    LocationName: "Hall A",
    Address: "123 Main St",
    LocationType: "Indoor",
    Capacity: 500,
    TableNumber: 50,
    RentCost: 1000.0,
    Description: "Spacious hall for events",
    IsDeleted: false,
    Status: false,
  },
  {
    LocationId: 2,
    LocationName: "Garden B",
    Address: "456 Park Ave",
    LocationType: "Outdoor",
    Capacity: 300,
    TableNumber: 30,
    RentCost: 500.0,
    Description: "Beautiful outdoor garden",
    IsDeleted: true,
    Status: false,
  },
  {
    LocationId: 3,
    LocationName: "Ballroom C",
    Address: "789 Elm St",
    LocationType: "Indoor",
    Capacity: 700,
    TableNumber: 70,
    RentCost: 1500.0,
    Description: "Elegant ballroom for formal events",
    IsDeleted: false,
    Status: false,
  },
  {
    LocationId: 4,
    LocationName: "Terrace D",
    Address: "1010 Sunset Blvd",
    LocationType: "Outdoor",
    Capacity: 200,
    TableNumber: 20,
    RentCost: 800.0,
    Description: "Terrace with stunning views",
    IsDeleted: false,
    Status: false,
  },
  {
    LocationId: 5,
    LocationName: "Conference Room E",
    Address: "1111 Tech Park",
    LocationType: "Indoor",
    Capacity: 100,
    TableNumber: 10,
    RentCost: 300.0,
    Description: "Modern conference room with AV setup",
    IsDeleted: false,
    Status: false,
  },
  {
    LocationId: 6,
    LocationName: "Banquet Hall F",
    Address: "2020 University Dr",
    LocationType: "Indoor",
    Capacity: 600,
    TableNumber: 60,
    RentCost: 1200.0,
    Description: "Large hall perfect for banquets and galas",
    IsDeleted: true,
    Status: false,
  },
  {
    LocationId: 7,
    LocationName: "Poolside G",
    Address: "3030 Beach Rd",
    LocationType: "Outdoor",
    Capacity: 250,
    TableNumber: 25,
    RentCost: 700.0,
    Description: "Relaxing poolside area for casual events",
    IsDeleted: false,
    Status: false,
  },
  {
    LocationId: 8,
    LocationName: "Rooftop H",
    Address: "4040 Skyview Dr",
    LocationType: "Outdoor",
    Capacity: 150,
    TableNumber: 15,
    RentCost: 600.0,
    Description: "Rooftop space with panoramic city views",
    IsDeleted: false,
    Status: false,
  },
  {
    LocationId: 9,
    LocationName: "Studio I",
    Address: "5050 Arts Center",
    LocationType: "Indoor",
    Capacity: 50,
    TableNumber: 5,
    RentCost: 200.0,
    Description: "Intimate studio space for small gatherings",
    IsDeleted: false,
    Status: false,
  },
  {
    LocationId: 10,
    LocationName: "Lounge J",
    Address: "6060 Riverfront",
    LocationType: "Indoor",
    Capacity: 80,
    TableNumber: 8,
    RentCost: 400.0,
    Description: "Chic lounge with river views",
    IsDeleted: true,
    Status: false,
  },
];


const initialAccounts = [
  {
    Username: "emily_white",
    Password: "whiteEmily@123",
    Fullname: "Emily White",
    Email: "emily.white@example.com",
    PhoneNumber: "0918765432",
    Image: "img/emily_white.jpg",
    Identity: "444455556666777",
    DateCreate: "2023-09-22 11:30:00",
    AccountStatus: true,
    IsDeleted: false,
  },
  {
    Username: "frank_castle",
    Password: "frank!castle@456",
    Fullname: "Frank Castle",
    Email: "frank.castle@example.com",
    PhoneNumber: "0812348765",
    Image: "img/frank_castle.jpg",
    Identity: "555566667777888",
    DateCreate: "2023-08-20 14:45:00",
    AccountStatus: false,
    IsDeleted: true,
  },
  {
    Username: "grace_hopper",
    Password: "graceTech!2024",
    Fullname: "Grace Hopper",
    Email: "grace.hopper@example.com",
    PhoneNumber: "0923456789",
    Image: "img/grace_hopper.jpg",
    Identity: "666677778888999",
    DateCreate: "2023-07-12 16:15:00",
    AccountStatus: true,
    IsDeleted: false,
  },
  {
    Username: "harry_potter",
    Password: "harryMagic123",
    Fullname: "Harry Potter",
    Email: "harry.potter@example.com",
    PhoneNumber: "0712349876",
    Image: "img/harry_potter.jpg",
    Identity: "777788889999000",
    DateCreate: "2023-06-28 10:00:00",
    AccountStatus: false,
    IsDeleted: true,
  },
  {
    Username: "isabella_green",
    Password: "greenLeaf@2023",
    Fullname: "Isabella Green",
    Email: "isabella.green@example.com",
    PhoneNumber: "0815674321",
    Image: "img/isabella_green.jpg",
    Identity: "888899990000111",
    DateCreate: "2023-05-23 09:30:00",
    AccountStatus: true,
    IsDeleted: false,
  },
  {
    Username: "jack_sparrow",
    Password: "pirateLife!789",
    Fullname: "Jack Sparrow",
    Email: "jack.sparrow@example.com",
    PhoneNumber: "0709871234",
    Image: "img/jack_sparrow.jpg",
    Identity: "999900001111222",
    DateCreate: "2023-09-10 12:20:00",
    AccountStatus: true,
    IsDeleted: false,
  },
  {
    Username: "kate_bell",
    Password: "bellKate#321",
    Fullname: "Kate Bell",
    Email: "kate.bell@example.com",
    PhoneNumber: "0601234567",
    Image: "img/kate_bell.jpg",
    Identity: "000011112222333",
    DateCreate: "2023-08-01 15:30:00",
    AccountStatus: false,
    IsDeleted: true,
  },
  {
    Username: "liam_wood",
    Password: "woodLiam456!",
    Fullname: "Liam Wood",
    Email: "liam.wood@example.com",
    PhoneNumber: "0502345678",
    Image: "img/liam_wood.jpg",
    Identity: "111122223333444",
    DateCreate: "2023-07-18 10:50:00",
    AccountStatus: true,
    IsDeleted: false,
  },
  {
    Username: "mia_clark",
    Password: "miaClark!2023",
    Fullname: "Mia Clark",
    Email: "mia.clark@example.com",
    PhoneNumber: "0403456789",
    Image: "img/mia_clark.jpg",
    Identity: "222233334444555",
    DateCreate: "2023-06-11 11:40:00",
    AccountStatus: false,
    IsDeleted: true,
  },
  {
    Username: "noah_stone",
    Password: "stoneNoah@789",
    Fullname: "Noah Stone",
    Email: "noah.stone@example.com",
    PhoneNumber: "0312345678",
    Image: "img/noah_stone.jpg",
    Identity: "333344445555666",
    DateCreate: "2023-05-29 13:15:00",
    AccountStatus: true,
    IsDeleted: false,
  }
];


const initialInvoices = [
  {
    InvoiceId: 1,
    ContractId: 1001,
    IssueDate: "2024-01-10T10:00:00",
    DueDate: "2024-01-20T23:59:59",
    PaymentMethod: "Credit Card",
    TotalAmount: 1500.5,
    InvoiceContent: "Payment for web development services",
    Status: "Pending",
  },
  {
    InvoiceId: 2,
    ContractId: 1002,
    IssueDate: "2024-02-05T09:30:00",
    DueDate: "2024-02-15T23:59:59",
    PaymentMethod: "Bank Transfer",
    TotalAmount: 2300.0,
    InvoiceContent: "Payment for mobile app development",
    Status: "Paid",
  },
  {
    InvoiceId: 3,
    ContractId: 1003,
    IssueDate: "2024-03-12T14:00:00",
    DueDate: "2024-03-22T23:59:59",
    PaymentMethod: "PayPal",
    TotalAmount: 1250.75,
    InvoiceContent: "Monthly maintenance and support",
    Status: "Overdue",
  },
  {
    InvoiceId: 4,
    ContractId: 1004,
    IssueDate: "2024-04-01T11:00:00",
    DueDate: "2024-04-11T23:59:59",
    PaymentMethod: "Cash",
    TotalAmount: 300.0,
    InvoiceContent: "Payment for graphic design services",
    Status: "Paid",
  },
  {
    InvoiceId: 5,
    ContractId: 1005,
    IssueDate: "2024-05-15T08:45:00",
    DueDate: "2024-05-25T23:59:59",
    PaymentMethod: "Credit Card",
    TotalAmount: 1890.99,
    InvoiceContent: "SEO optimization services",
    Status: "Pending",
  },
];

export {
  initialContracts,
  stockRequests,
  initialServices,
  initialEvents,
  initialLocations,
  initialAccounts,
  initialInvoices,
};
